# NAME|TYPE|SOURCE|PARTITION|FS_TYPE|PBS_REPOSITORY|BACKUP_ID
shares|lvm|vg0/vm-103-disk-shares||xfs|pvs@pbs!files@pbs.lan.lnar.net:files|cloudnas-shares
immich|zfs|dpool/data/images/vm-103-disk-immich|1|xfs|pvs@pbs!files@pbs.lan.lnar.net:files|cloudnas-immich
